identidock:
  build: .
  ports:
    - "5000:5000"
  environment:
    ENV: DEV
  volumes:
    - ./app:/app
  # links:
  #   - dnmonster
  # depends_on:
  #   - dnmonster

# dnmonster:
#   image: royletron/robohash
#   ports:
#     - "3001:3001"